app/common.js
app/event/recruit_button.js

・参加ボタンのエラーメッセージ出る問題を修正。
・サーモンランの？ブキのときに:question:ではなく絵文字を直接返すように修正

fix:recruit button and salmon run undefined emoji

---

app/cmd/buki.js
app/cmd/recruit.js
app/event/recruit_button.js
app/index.js
app/tts/voice_bot_node.js
package.json

読み上げメッセージにメンションがあった場合に名前に置き換える処理が動作いなくなっていたので修正
- 普通のメンションはもともと1つ目しか変換してなかったので複数入ってても動くように再帰処理にして対応
- ロールメンション、ニックネームメンション、チャンネル名にも同様に対応

読み上げ内のメンション対応

---

app/cmd/recruit.js
app/cmd/recruit/button_components.js
app/cmd/recruit/canvas_components.js
app/cmd/recruit/league_recruit.js
app/cmd/recruit/other_game_recruit.js
app/cmd/recruit/private_recruit.js
app/cmd/recruit/regular_recruit.js
app/cmd/recruit/salmon_recruit.js
app/common.js
app/event/recruit_button.js
app/index.js
constant.js
register.js

- ナワバリ募集コマンドの追加
- 代理〆の追加
- ボイスチャンネルオプションを追加(サーモン、リグマ(now)、ナワバリ(now)のみ)
- Canvasの縁付きテキストのコードを共通化
- 募集をリプライで送信する形に変更
- 参加時のEmbed変更
- 別ゲー、プラベ募集の募集人数のオプションを一部Stringに変更

create regular recruit & VC Option

---

app/event/recruit_button.js
db/create_table.sql
db/recruit_delete.js
db/recruit_insert.js
db/recruit_select.js
register.js

- ephemeralで参加完了メッセージ（従来どおり）
- 二回目以降はephemeralで参加済みを伝えるメッセージ
- メンション付きのメッセージが送信され、通知がくる
- 15秒後に削除される（通知だけ残り、チャット欄のログは流れない）
- 参加表明一覧に参加者が追加される
- 参加表明一覧からボタン押した人が削除される
- ホストに通知メッセージが飛ぶ 
- ephemeralでホスト以外はキャンセルできないメッセージ
- 従来どおり、キャンセルされる
すべて従来どおり

参加ボタンの仕様変更

---

app/cmd/splat3/recruit/anarchy_recruit.js
register.js

- ウデマエに差があっても一緒にできるらしい
- ウデマエを指定したらウデマエロールにメンション、指定しなかったらeveryoneメンションするよう変更

バンカラマッチの募集コマンドからウデマエの必須条件を削除

---

app/cmd/splat3/show.js
app/cmd/splat3/stageinfo.js
app/common.js
app/index.js
register.js

- ステージ情報チャンネルで出力するステージ情報はフェス期間中のスケジュールはnullになるのでエラーにならないよう出力情報を変更
- show xxコマンドでは各ルールの代わりにフェス情報を表示するように修正
- getRegularを配列でなくObjectで返すように修正

フェス期間中のステージ情報対応

---

app/event/join.js

Fixes #314
メンバー参加して10分後に新入部員ロールを付与する処理で、
10分以内にメンバーがサーバー退出した場合にmember.roles.setでmemberが取得できずに落ちてたのが原因
ロール付与の直前にfetchして存在確認することで回避するよう修正

FIX: DiscordAPIError: Unknown Memberが発生する

---

app/cmd/other/recruit/other_game_recruit.js
app/cmd/splat2/recruit/league_recruit.js
app/cmd/splat2/recruit/private_recruit.js
app/cmd/splat2/recruit/regular_recruit.js
app/cmd/splat2/recruit/salmon_recruit.js
app/cmd/splat3/recruit/anarchy_recruit.js
app/cmd/splat3/recruit/fes_recruit.js
app/cmd/splat3/recruit/private_recruit.js
app/cmd/splat3/recruit/regular_recruit.js
app/cmd/splat3/recruit/salmon_recruit.js
app/common/button_components.js
app/event/recruit_button.js

-  プラベ募集は以前のボタンと互換性なし
- ロードボタン用のアニメーション絵文字を指定する環境変数追加
- 一部オブジェクトをinteractionから直接拾うように変更(interaction.messageとかはそのまま取れそうなので)
- 一部処理をまとめてAPI叩く回数を少し減らした

募集ボタン押下時にボタンを一時的に無効化

---

app/cmd/other/recruit/other_game_recruit.js
app/cmd/splat2/recruit/league_recruit.js
app/cmd/splat2/recruit/private_recruit.js
app/cmd/splat2/recruit/regular_recruit.js
app/cmd/splat2/recruit/salmon_recruit.js
app/cmd/splat3/recruit/anarchy_recruit.js
app/cmd/splat3/recruit/fes_recruit.js
app/cmd/splat3/recruit/private_recruit.js
app/cmd/splat3/recruit/regular_recruit.js
app/cmd/splat3/recruit/salmon_recruit.js
app/event/recruit_button.js

募集が被ったときにまだ〆てない募集をわかりやすくするためにピン留めする
スレッドだとスレッド内でのやりとりに気づきにくいため、募集チャンネル内でのやりとりはそのままにし、継続中の募集があるかどうかをピン留めで確認できるようにする。
- 募集時(15秒経過後)にピン留め
- キャンセル、〆ボタン押したときにピン留め解除

募集中のメッセージをピン留め

---

app/event/recruit_button.js

募集削除ボタンの処理中に募集が経ってら15秒経過した場合に募集ボタン自体が削除できないエラー出てたので、
try-catchで無視するように変更

fix: 募集削除ボタンのエラー修正

---

register.js

- stgに2重にコマンド登録されてたので削除用
- guild, globalのスラコマ登録前に使ってない方のコマンドを空で上書き

update: サーバー起動時に使ってない方のコマンドを削除

---

app/cmd/other/recruit/other_game_recruit.js
app/cmd/splat2/recruit/league_recruit.js
app/cmd/splat2/recruit/regular_recruit.js
app/cmd/splat3/recruit/anarchy_recruit.js
app/cmd/splat3/recruit/fes_recruit.js
app/cmd/splat3/recruit/private_recruit.js
app/cmd/splat3/recruit/regular_recruit.js
app/cmd/splat3/recruit/salmon_recruit.js
app/common/button_components.js
app/event/recruit_button.js

- 募集がしまっててもキャンセルされても募集から2時間後に自動〆のメッセージで上書きされるのを修正
- 募集のヘッダー部分のメッセージを募集がしまっても不自然に見えないように変更
- 募集時すぐピンどめするように変更(募集がすぐに閉じられるorキャンセルされたときに残ってしまうため)
- 自動〆時にメンバーリストが出なかったのを修正
- 自動〆時はメンバーリストに自動〆であることがわかるように明記

fix: 自動〆の処理変更と募集メッセージの変更

---

app/cmd/splat3/show.js
app/cmd/splat3/stageinfo.js
register.js

Fixes #436
- ステージ情報チャンネル用コマンド `stageinfo` でXマッチを表示
- `show now` `show next` でXマッチを表示
- `show run` で2つ先のシフトまで表示

showコマンド、ステージ情報にXマッチを追加 、サーモンランのシフト情報を２つ先まで表示

---

app/event/dispandar.js
app/manager/memberManager.js

- エラー理由
common.js内でMemberManager.jsを呼び出した時に最初にcommonから別のモジュールをインポートしようとして循環インポートになったため。
- 修正内容
module.exportsを先頭にもってくることで読み込みタイミングを変えた
[参考リンク](https://qiita.com/gologo13/items/b026f7debdd80c08d499)

fix: dispanderのエラー修正

---

app/cmd/admin-cmd/environment_variables/delete_variables.js
app/cmd/admin-cmd/environment_variables/set_variables.js

- 対象のprocess.envにundefindを代入するのではなく、process.envから直接削除するように変更
- valueが'hogehoge'の場合process.envの値が''hogehoge''になってしまうのを修正
- 保存時の改行コードを `\n` ( LF ) に統一 ( GCPだと改行入る問題の対応 ) <- 直ってるかは不明
- 読み込み時の改行コードは CR or LF or CRLF

fix: コマンドで環境変数削除後に再起動しないとうまく動作しない問題を修正

---

app/event/dispandar.js
app/manager/channelManager.js

ChannelManagerも直接fetchすることで、チャンネルタイプによってチャンネル検索の仕方を変える必要なくオブジェクトが拾える。
dispanderと処理がほぼ同じなのでdispanderもMessageManagerから呼び出すように変更

fix: フォーラムチャンネルのチャンネルオブジェクトが拾えない問題の修正

---

app/event/reactions.js
app/index.js
db/model/reactions.js
db/model/total_reactions.js
db/reactions_service.js
db/total_reactions_service.js

以下を追加
- リアクションされたユーザーごとに絵文字やチャンネルごとに回数を記録するテーブル
- リアクションごとのseq管理と合計回数を記録するテーブル

feat:リアクションされたユーザーと絵文字をテーブルに記録する機能を追加

---

app/cmd/admin-cmd/enableButton.js
app/index.js
constant.js
register.js

使うときは該当ボタンのあるメッセージを右クリック
アプリ > ボタンを有効化する
スラコマ版は削除
一応チャンネル管理権限見るように設定したけど、
連携サービスから表示対象選べたのでそっちで使用者制限かけましょう

update: ボタン有効化コマンドをコンテキストメニューに移動

---

app/cmd/splat3/show.js
app/cmd/splat3/stageinfo.js

splatoon3inkからリグマスケジュールが消えたので取得してる部分をコメントアウト

fix: リグマ関連のスケジュールデータ取得処理をコメントアウト

---

app/common/others.js

webhookや退部したユーザーのようにmemberが取れない時に不明なユーザーとしてembedを作成するように変更

fix: webhook, 退部済みユーザーのdispander表示を修正

---

src/app/index.ts
src/db/members_service.ts

- GMU & UU デバッグ用ログの追加 ( searchAPIする必要ない説の検証)
- userUpdate時はDBにないプロフィールの登録をしないように変更(GMUは登録あり)
- userUpdate時はDBからguildId取得

fix: 環境変数に入れていないguildのuserUpdateエラーの修正

---

src/app/common/apis/splatoon3.ink/splatoon3_ink.ts
src/app/event/cron/stageinfo.ts

フェス期間中APIからマッチ情報が取れない場合、`MatchInfo`自体を`null`で返却していたので取れない項目のみを`null`で返すように変更

fix: ステージ情報のエラー修正

---

src/app/common/apis/splatoon3.ink/splatoon3_ink.ts
src/app/common/apis/splatoon3.ink/types/fest_properties.ts

bankara_propertiesとfest_propertiesプロパティを見比べる限り、bankaraMatchSettingsと同じ構造になった？のでフェスだけの話だと思ってます。
とりあえず募集ができない障害が起きてるのでこれでいきます。

fix: schedules.jsonの構造が変わったのに合わせて変更

---

src/app/feat-admin/unique_role_settings/show_all_unique_role.ts

- チャンネルメンション `<#${uniqueRole.roleId}>` を役職メンション `<@&{uniqueRole.roleId}>` に置き換えました。

fix:ロールメンションのフォーマット修正

---

package.json

chore: Prismaクライアントのバージョンを本体と同じに変更

---

src/app/constant/button_id.ts
src/app/feat-recruit/buttons/create_join_request_buttons.ts
src/app/feat-recruit/interactions/buttons/cancel_event.ts
src/app/feat-recruit/interactions/buttons/cancel_notify_event.ts
src/app/feat-recruit/interactions/buttons/confirm_join_request.ts
src/app/feat-recruit/interactions/buttons/join_event.ts
src/app/feat-recruit/interactions/buttons/join_notify_event.ts
src/app/feat-recruit/interactions/buttons/other_events.ts
src/app/feat-recruit/interactions/buttons/recruit_button_handler.ts
src/app/feat-recruit/interactions/buttons/send_notify_to_host.ts

募集参加時に参加OKかどうかを1ボタンで返信できる機能の追加
- 新たに募集用パラメータを2種追加
参加ボタン→参加通知メッセージ→承認・拒否に応じてメッセージ送信
拒否されたときは、自動的に参加取り下げ
30分後にボタンは消える(逆に〆ても消えない・〆た状態で押すと消える)
承認時はVCに募集主がいれば案内、いなけば待つように伝える

feat: 参加の返信をある程度省略するボタンを作成

---

src/app/common/manager/member_manager.ts
src/app/event/rookie/set_rookie.ts
src/app/event/vctools_sticky/radio_request.ts
src/app/handlers/message_handler.ts
src/app/index.ts
src/db/member_service.ts

- もう使用しない一括DB登録コマンドの削除
- `searchDBMemberById`の新入部員ロールの有無確認部分をMemberService側で行うように変更
- `GuildMemberAdd`時にDBにMember保存してなかったのを修正
- `MemberUpdate`, `UserUpdate`の処理変更
- 変数名`dbMember`を`storedMember`に変更
`[[WARN] MemberManager] member Icon invalid => Icon URL was updated successfully.`
の警告が大量に出てたのでログの情報追加 (多分UserUpdateのときの処理がうまく動いてなかったっぽい？)

fix: 新入部員をDBに保存してなかったのを修正

---

src/constant.ts

https://placehold.jp/ のAdvancedのうち、文字サイズやテキストをパラメータに含めると503エラーになる模様
とりあえずblankAvatarで使ってるURLに置き換えて応急処置します。

fix: placehold.jpが503になるのでblankAvatar用の画像URLで代用

---

src/app/common/webhook.ts
src/app/feat-recruit/interactions/buttons/cancel_event.ts
src/app/feat-recruit/interactions/buttons/cancel_notify_event.ts
src/app/feat-recruit/interactions/buttons/close_event.ts
src/app/feat-recruit/interactions/buttons/close_notify_event.ts
src/app/feat-recruit/interactions/buttons/confirm_join_request.ts
src/app/feat-recruit/interactions/buttons/delete_event.ts
src/app/feat-recruit/interactions/buttons/join_event.ts
src/app/feat-recruit/interactions/buttons/join_notify_event.ts
src/app/feat-recruit/interactions/buttons/recruit_button_handler.ts
src/app/handlers/command_handler.ts
src/app/handlers/context_handler.ts
src/app/logs/buttons/recruit_button_log.ts
src/app/logs/commands/command_log.ts
src/app/logs/modals/recruit_modal_log.ts

- コマンドログ実行処理のawait解除(DB周りでエラーでたら戻す)
- ボタン押下時に Unknown Interactionがでたら再度ボタンを押すように促す。
- 募集用のボタンで考え中にする処理をハンドラーで行うように変更 (それに伴いephemeral処理変更)

perf: Unknown Interaction対策

---

src/app/feat-recruit/common/auto_close.ts
src/app/feat-recruit/common/condition_checks/schedule_check.ts
src/app/feat-recruit/common/create_recruit/arrange_command_data.ts

- サーモンラン関連イベントの条件チェックを関係する募集以外で行われないように変更
- 自動〆時に募集情報がDBにあるかチェックするように変更
- 条件チェックでエラーが出た場合にエラーログを出さないように修正

fix: 募集が〆っていても自動〆の処理が行われるのを修正

---

src/app/feat-recruit/common/auto_close.ts
src/app/feat-recruit/common/create_recruit/arrange_command_data.ts
src/app/feat-recruit/common/create_recruit/arrange_modal_data.ts
src/app/feat-recruit/common/create_recruit/remove_delete_button.ts
src/app/feat-recruit/common/create_recruit/send_recruit_message.ts
src/app/feat-recruit/interactions/anarchy_recruit.ts
src/app/feat-recruit/interactions/event_recruit.ts
src/app/feat-recruit/interactions/fest_recruit.ts
src/app/feat-recruit/interactions/registerRecruitData.ts
src/app/feat-recruit/interactions/regular_recruit.ts
src/app/feat-recruit/interactions/salmon_recruit.ts
src/app/feat-recruit/types/recruit_condition_error.ts
src/app/feat-recruit/types/recruit_data.ts

- エラーログ通知を行う関数の呼び出し位置の修正
- コマンド募集とモーダル募集で全く同じ型・クラスを定義していたので共通化
- 募集データ成形時にエラーが出た場合にそのエラーをそのまま投げるように修正

fix: モーダル募集時に条件エラーがでるとエラーログに通知される問題を修正

---

src/app/handlers/command_handler.ts
src/app/handlers/context_handler.ts
src/app/index.ts
src/app/logs/commands/command_log.ts

- コマンドログでGuildのフェッチとDBからメンバー情報検索を削って、interaction.memberが取れない(Raw)データが送られてきた場合はユーザー情報で表示するように変更
- キャッシュされてないGuildからInteractionが来たときにエラーログが出るように変更
- 頻度が低そうならキャッシュされてない場合はフェッチし直すように変更したい
(interaction.guild, interaction.memberのチェックせずに済むため)
- エラーログにしてるのはコンソールログだと気付けなさそうだからです。

perf: コマンドログ送信処理を待たずにコマンド処理を行うように変更
