- .gitignore
- .vscode/settings.json
- app/common.js
- app/dispandar.js
- app/index.js
- app/join.js
- app/suggestion-box.js
- package-lock.json
- package.json
- ご意見投稿用にチャンネルに投稿されたらプライベートチャンネルを作成
- 投稿されたテキストを作成したチャンネルに貼り付けて通知
- 対応が完了したら内容をすべてご意見箱アーカイブ用のチャンネルに移行
- 投稿者からも見えなくする
- チャンネルの削除はとりあえず手動でやる
> ご意見箱をGoogleフォームからDiscord内完結へ

- app/index.js
- app/suggestion-box.js
・メッセージ投稿してからだと最初のメッセージが誰かに見られる可能性があるため
・リアクションするメッセージを`!init`コマンドでbotに投稿させ、最初のリアクションをつけるようにした
(不具合起きてやり直したいときもコマンドでできるように)
> 通報チャンネルをリアクションで作成できるように修正

- app/delete_token.js
- app/index.js
> create delete_token function

- app/delete_token.js
> fix delete_token.js

- app/cmd/recruit.js
- msg.channel.sendからmsg.replyに変更
- ドキュメントフォーマットがかかった
> change from "send" to "reply"

- app/cmd/recruit.js
- app/cmd/recruit_canvas.js
- app/event/recruit_button.js
> Recruit canvas

- app/cmd/recruit.js
- app/cmd/recruit_canvas.js
> fix recruit condition

- app/cmd/recruit.js
- app/cmd/recruit_canvas.js
- app/event/dispandar.js
メッセージリンクでの引用と一緒にメッセージを打つとクラッシュする問題を修正
> Fix quotation

- app/index.js
joinのロビー取得と同じようにキャッシュがなければfetchするようにしてみた。
> fix:退部ログチャンネルが取得できない場合に対応

- app/common.js
- app/event/recruit_button.js
- app/index.js
・参加ボタンのエラーメッセージ出る問題を修正。
・サーモンランの？ブキのときに❓ではなく絵文字を直接返すように修正
> fix:recruit button and salmon run undefined emoji

- app/event/recruit_button.js
- app/tts/discordjs_voice.js
- app/tts/voice_bot_node.js
- VC接続中に落ちる問題
- 絵文字1文字のときに読み上げしないように修正
- 参加ボタンのエラーメッセージを出力しないよう修正
> Fixed some bugs

- app/common.js
- app/reaction/suggestion-box.js
メッセージリンク貼るときのことだけ考えて直してたメソッドをご意見箱のアーカイブにも適用させるために修正した
> Fix suggestion box

- app/cmd/experience.js
- app/cmd/recruit_canvas.js
> change the font specification method

- app/cmd/buki.js
- app/cmd/recruit.js
- app/event/recruit_button.js
- app/index.js
- package.json
herokuにpushするのmainじゃないといけないから、間違ってmainブランチにコミットしちゃったのでstgにPR送るね
> 募集コマンドのメッセージを削除してもボタンが動くように修正

- app/cmd/kansen.js
- js-combinatoricsをアップデートしたのが原因
- text in voiceはピン留めできないのでそれも修正
> kansenコマンド使うと落ちる #180

- app/cmd/voice_locker.js
- register.js
> update voice locker

- app/cmd/other_game_recruit.js
- app/cmd/private_recruit.js
- app/event/recruit_button.js
- app/index.js
- constant.js
- register.js
別ゲー募集コマンドをプライベートマッチ用に移植しただけです。
> add private match cmd

- app/cmd/other_game_recruit.js
- app/cmd/private_recruit.js
ついでに別ゲーはゲームタイトルをsetTitleに追加しました
> embedのauthorをコマンド叩いた人にする

- app/cmd/other_game_recruit.js
- app/cmd/private_recruit.js
- app/event/recruit_button.js
- app/index.js
- constant.js
- register.js
内容はこっちのコメントみてもろうて
https://github.com/shngmsw/ikabu/pull/207
> プラベ募集コマンドの追加

- app/cmd/recruit/button_components.js
- app/cmd/recruit/canvas_components.js
- app/cmd/recruit/league_recruit.js
- app/cmd/recruit/other_game_recruit.js
- app/cmd/recruit/private_recruit.js
- app/cmd/recruit/salmon_recruit.js
- app/common.js
- app/event/recruit_button.js
- app/index.js
- constant.js
- register.js
- サーモンラン募集コマンドの実装
- キャンバスで使うコードとボタン作るコードを共通化
- 削除ボタンの秒数を15秒に変更
- 別ゲー、プラベ募集に削除ボタン追加
- 削除ボタンが消えてからキャンセルボタン、〆ボタンが出るように変更
- 削除ボタンの位置を変更
> サーモンラン募集コマンドの実装

- app/cmd/recruit.js
- app/cmd/recruit/other_game_recruit.js
- app/cmd/recruit/private_recruit.js
- app/cmd/recruit/salmon_recruit.js
> delete auto close

- app/cmd/recruit/regular_recruit.js
- app/cmd/recruit/salmon_recruit.js
- サーモン募集、ナワバリ募集の募集投稿レイアウトを他の募集と同様に修正
> fix recruit view

- app/cmd/friendcode.js
- app/handler.js
- app/index.js
- constant.js
- db/fc_select.js
- register.js
#230 の対応
- 通常コマンドを削除
- スラッシュコマンドを追加
- ブキチを指定しても反応しないように修正
> add slash friend code command

- app/common.js
- app/index.js
> fix close command

- app/cmd/splat3/recruit/regular_recruit.js
- app/index.js
- app/manager/channelManager.js
- スプラ3用のレギュラー募集作成
- スプラ2用の関数名変更
> create regular recruit command for splatoon3

- app/cmd/splat3/recruit/private_recruit.js
- app/common/button_components.js
- app/event/recruit_button.js
- app/index.js
- register.js
> create private recruit for splatoon3

- app/cmd/splat3/recruit/anarchy_recruit.js
- register.js
> #265 release

- app/cmd/splat2/recruit/league_recruit.js
- app/cmd/splat2/recruit/regular_recruit.js
- app/cmd/splat2/recruit/salmon_recruit.js
- app/cmd/splat3/recruit/anarchy_recruit.js
- app/cmd/splat3/recruit/regular_recruit.js
- app/cmd/splat3/recruit/salmon_recruit.js
- app/event/recruit_button.js
- Fixes #273
- ホストがVCにいる場合はtext in voiceに募集メッセージのリンク付きで参加表明をお知らせ
> 募集のホストへの通知

- app/cmd/splat3/show.js
- app/common.js
> fix bankara show

- app/event/recruit_button.js
- db/create_table.sql
- db/recruit_select.js
- 参加表明一覧がボタン押下順になるように修正
- recruitテーブルにcreatedを追加
- ホストへの通知仕様を変更
- VC接続中でも募集チャンネルにメンション付きで通知
- 募集チャンネルのメッセージ削除までの時間を15秒→5分に変更
- text in voiceへはメンションなしでメッセージ送信
> 参加ボタン処理の修正

- app/cmd/splat3/buki.js
- app/handler.js
- register.js
- apiのurlを変更
- ブキ種にワイパーとストリンガーを追加
> ブキコマンドのSplatoon3対応

- app/cmd/splat2/recruit/league_recruit.js
- app/cmd/splat2/recruit/regular_recruit.js
- app/cmd/splat2/recruit/salmon_recruit.js
- app/cmd/splat3/recruit/anarchy_recruit.js
- app/cmd/splat3/recruit/fes_recruit.js
- app/cmd/splat3/recruit/regular_recruit.js
- app/cmd/splat3/recruit/salmon_recruit.js
- app/common.js
- app/event/recruit_button.js
- `member.user.displayAvatarURL` -> `member.displayAvatarURL`
- `member.user.username` -> `member.displayName`
- フェス募集のコマンド説明のアップデート
> 募集・参加時のユーザーアイコンをサーバープロフィールのものに変更

- app/cmd/other/friendcode.js
- app/cmd/other/help.js
- app/index.js
- register.js
Close #288 
- メンバー指定削除
- 削除ボタンを追加
> フレンドコードのコマンドメッセージを消せるように変更

- app/cmd/splat3/recruit/regular_recruit.js
> Fix regular recruit

- app/cmd/admin-cmd/ban.js
- app/cmd/admin-cmd/createRoom.js
- app/cmd/admin-cmd/deleteCategory.js
- app/cmd/admin-cmd/deleteChannel.js
- app/cmd/admin-cmd/manageRole.js
- app/cmd/other/friendcode.js
- app/cmd/other/recruit/other_game_recruit.js
- app/cmd/splat2/recruit/league_recruit.js
- app/cmd/splat2/recruit/private_recruit.js
- app/cmd/splat2/recruit/regular_recruit.js
- app/cmd/splat2/recruit/salmon_recruit.js
- app/cmd/splat3/recruit/anarchy_recruit.js
- app/cmd/splat3/recruit/fes_recruit.js
- app/cmd/splat3/recruit/regular_recruit.js
- app/cmd/splat3/recruit/salmon_recruit.js
- app/event/recruit_button.js
#320 の修正
- ローカルだと該当エラー出なかったのでとりあえずguildをfetchして様子見る
- deleteCategoryでチャンネル削除するたびにfetchするように変更
https://github.com/shngmsw/ikabu/blob/ddb9fe7c7fe7de9a66a9a5509b688c80eb4f52d9/app/cmd/admin-cmd/deleteCategory.js#L113-L123
> changed to fetch guild

- app/event/recruit_button.js
> fix close button

- app/index.js
Fixes #332 
を修正するついでにサーバーの人数を表示するように変更
> Fixes #332 

- app/event/recruit_button.js
処理前にdeferReplyをおいて、deleteReply -> followUpとすることでephemeralのtrue, falseを切り替え
> 募集ボタンで処理に時間がかかるとリアクション失敗になってしまうのを修正

- app/cmd/other/help.js
- app/cmd/other/recruit/other_game_recruit.js
- app/common.js
- app/event/recruit_button.js
- register.js
> DbD募集コマンドをOverwatch2募集コマンドに変更

- app/cmd/other/recruit/other_game_recruit.js
> change role name in ow recruit

- app/event/recruit_button.js
> 変数増やして処理を二回に分けた

- app/cmd/other/help.js
- app/cmd/other/team_divider/divider.js
- app/cmd/other/team_divider/dviderDB.js
- app/index.js
- constant.js
- db/create_table.sql
- register.js
> チーム分け機能の実装

- app/cmd/other/team_divider/divider.js
> fix init buttons

- app/cmd/admin-cmd/enableButton.js
- app/cmd/other/team_divider/divider.js
- app/cmd/other/team_divider/dviderDB.js
- app/common/button_components.js
- app/index.js
- constant.js
- register.js
- ボタンの仕様変更
- 過去の試合に戻れるように変更
- 戦績表示を切り替えられるように変更
- 併せてDB構成を変更
> update team divider commands

- app/cmd/admin-cmd/enableButton.js
- app/cmd/other/team_divider/divider.js
- app/common/button_components.js
- app/index.js
interaction.message.componentsは拾えるだろうという予測
だめそうな部分は先にメッセージfetchすればいいので関数内でfetchするのをやめる
> remove message fetch process

- app/event/recruit_button.js
- 募集の参加者一覧に参加メンバーリストのlengthを表示
> update: 募集の参加者一覧に現在の参加数を表示

- app/event/recruit_button.js
> fix: ピン留め関連のバグを修正

- app/cmd/other/recruit/other_game_recruit.js
- app/cmd/splat2/recruit/league_recruit.js
- app/cmd/splat2/recruit/private_recruit.js
- app/cmd/splat2/recruit/regular_recruit.js
- app/cmd/splat2/recruit/salmon_recruit.js
- app/cmd/splat3/recruit/anarchy_recruit.js
- app/cmd/splat3/recruit/fes_recruit.js
- app/cmd/splat3/recruit/private_recruit.js
- app/cmd/splat3/recruit/regular_recruit.js
- app/cmd/splat3/recruit/salmon_recruit.js
- app/event/recruit_button.js
エラー内容
- 募集が消されていたら関数returnして2時間後に何も行わないように変更
> fix: 募集が消されたらreturnするように変更

- app/common/button_components.js
- app/event/recruit_button.js
- ボタンを有効化を使えるように処理変更
- 不要になった関数の削除
> change: ボタンの処理を変更

- app/event/recruit_button.js
ボタン用の関数の戻り値が配列になってたのに、さらに配列に入れてたのでエラー出てた
> Fix recruit button

- app/event/recruit_button.js
> fix: プラベ募集の〆ボタンが復帰する問題の修正

- app/cmd/splat3/recruit/anarchy_recruit.js
- app/cmd/splat3/recruit/fes_recruit.js
- app/cmd/splat3/recruit/regular_recruit.js
エラー出る要素が思いつかないけど、キャンセルしたあと、たまたま募集削除ボタンを消すタイミングと募集削除ボタンを押したタイミングが一致した時用の処理
> fix: 2時間後に募集削除されてないかチェック

- app/cmd/other/voice_mention.js
- app/index.js
- app/manager/memberManager.js
- config/log4js-console-config.json
- config/log4js-stdout-config.json
- constant.js
- register.js
`/ボイスメンション vcmention`
- メッセージは省略不可・チャンネルは省略可
- チャンネル省略時はコマンド使用チャンネルのメンバーにメンション
- テキストチャンネルで使用する場合はVC指定必須
プラベロビーで両チームにメンション送りたい時とか用、2回送る必要はあるので面倒そうではあるけど
- 指定するチャンネルはメンション対象のいるチャンネルで、投稿されるのはコマンド使用チャンネル
> add: VCメンバー全員にメンションを送るコマンドを実装

- app/cmd/admin-cmd/manageRole.js
もしかしたらfetchすれば人数制限なくロールつけれるのでは？と思ったので変更
> update: ロール割当・解除でロールコレクションをフェッチするように変更

- app/cmd/splat3/recruit/salmon_recruit.js
> fix:salmon recruit

- app/event/command_log.js
> fix: インポート忘れ修正

- app/cmd/other/voice_locker.js
- app/index.js
- constant.js
- register.js
`/voice_channel`から`/ボイスロック vclock`にコマンド名変更
オプション名も`limit` -> `人数`に変更
> update: コマンド名変更(voice_channel -> vclock)

- app/cmd/other/recruit/other_game_recruit.js
- app/cmd/splat3/recruit/anarchy_recruit.js
- app/cmd/splat3/recruit/fes_recruit.js
- app/cmd/splat3/recruit/private_recruit.js
- app/cmd/splat3/recruit/regular_recruit.js
- app/cmd/splat3/recruit/salmon_recruit.js
- app/common.js
- app/event/join.js
- app/event/recruit_button.js
> refactor: sleepの関数化

- app/tts/discordjs_voice.js
- app/tts/voice_bot_node.js
- config/log4js-console-config.json
- config/log4js-stdout-config.json
変更内容
- 読み上げの200文字カットが機能してなかったので修正
- 読み上げ時のエラーをキャッチするように変更
> 間違えてmainに直プッシュしたのでstg反映用

- app/cmd/admin-cmd/environment_variables/delete_variables.js
- app/cmd/admin-cmd/environment_variables/set_variables.js
- app/cmd/admin-cmd/environment_variables/show_variables.js
- app/cmd/admin-cmd/environment_variables/variables_handler.js
- app/index.js
- constant.js
- register.js
.envの書き換えと現在のプロセスのprocess.envの変更を行うコマンドの追加
`/環境変数設定 表示` -> 表示を行うコマンド
`/環境変数設定 登録更新` -> 登録・更新を行うコマンド
`/環境変数設定 削除` -> 削除を行うコマンド
一応チャンネル管理権限あるかチェックかけてます。
> add: 環境変数設定コマンドの追加

- app/tts/discordjs_voice.js
- app/tts/voice_bot_node.js
> fix: 読み上げ開始コマンドでエラー時の処理変更

- app/cmd/admin-cmd/environment_variables/delete_variables.js
- app/cmd/admin-cmd/environment_variables/set_variables.js
- app/cmd/admin-cmd/environment_variables/show_variables.js
- app/cmd/admin-cmd/environment_variables/variables_handler.js
- app/manager/channelManager.js
環境変数にカテゴリIDを記載
`CATEGORY_PARENT_ID_ADMIN_ONLY`
> update: 管理者限定以外のカテゴリで環境変数設定コマンドを使用したときにエラー表示

- app/event/rookie/remove_rookie.js
- app/event/rookie/send_questionnaire.js
- app/event/rookie/set_rookie.js
- app/index.js
#469 
`QUESTIONNAIRE_URL`でURL設定
URLが設定されていなければリプライを送らない ( 今までと同じ )
- 新入部員関係のファイルの場所と名称変更
それぞれの文面はとりあえず適当に考えたので変えたければ言って下さい。
> add: 新入部員ロールが外れる時にアンケート送信

- app/event/rookie/remove_rookie.js
- app/event/rookie/send_questionnaire.js
- app/index.js
- 新入部員ロールが外れる際に送るアンケートURLが既存部員のURLになっていたのを修正
> fix: アンケートURLの修正

- app/event/dispandar.js
- app/event/recruit_button.js
- app/manager/channelManager.js
`const header_message = await searchMessageById(guild, interaction.channel, header_msg_id);`
みたいにchannelそのものを渡してるところをid渡すように修正
> searchChannelByIdの検索を2段階に修正,searchMessageByIdの呼び出し箇所を修正

- app/common/apis/splatoon3_ink.js
フェス時は`get〇〇Data(data, num)`で開始時刻と終了時刻以外のデータを入れないように変更
> fix: データを整形するときにフェスチェックを入れるように変更

- app/buttons/recruit/event/recruit_button_events.js
- チャンネルのtypeがGuildVoiceかチェックするように変更
- プラベ募集ボタンの参加時通知の仕様を他募集とおなじになるように変更
- チャンネル検索で関数使用するように変更
> fix: ステージチャンネルに募集主がいるときに参加ボタンでエラーが出る問題を修正

- app/cmd/admin-cmd/enableButton.js
- constant.js
- register.js
- チャンネルオプションのrequireを外した
- チャンネル指定なしの場合コマンド使用チャンネルを自動取得
- ボタン有効化にコマンド名変更
> update: ボタン有効化コマンドでチャンネルを自動取得

- app/buttons/recruit/event/recruit_button_events.js
member.voice.channelが拾えない条件の拾い忘れを修正
> fix: 募集主がVCにいない時に参加ボタンでエラーが出る問題の修正

- app/cmd/other/voice_locker.js
- app/index.js
- app/tts/discordjs_voice.js
> update: VC退出時に読み上げをkill

- app/event/support/edit_tag.js
- app/event/support/resolved_support.js
- app/event/support/send_support_close_button.js
- app/event/support/tag_ids_embed.js
- app/index.js
Closes #505 
環境変数追加
- `CHANNEL_ID_SUPPORT_CENTER` : サポートセンターのチャンネルID
- `TAG_ID_SUPPORT_PROGRESS` : 対応中タグのID
- `TAG_ID_SUPPORT_RESOLVED` : 回答済みタグのID
> feat: サポートセンターの自動タグ付け機能の実装

- app/buttons/recruit/components/create_recruit_buttons.js
- app/buttons/recruit/event/recruit_button_events.js
- app/cmd/other/recruit/other_game_recruit.js
- app/cmd/splat3/recruit/anarchy_recruit.js
- app/cmd/splat3/recruit/fes_recruit.js
- app/cmd/splat3/recruit/private_recruit.js
- app/cmd/splat3/recruit/regular_recruit.js
- app/cmd/splat3/recruit/salmon_recruit.js
- app/modals/recruit/event/anarchy_recruit_modal.js
- app/modals/recruit/event/fes_recruit_modal.js
- app/modals/recruit/event/regular_recruit_modal.js
- app/modals/recruit/event/salmon_recruit_modal.js
- ボタンに画像2枚目のメッセージID追加
header -> image1に名前変更 (分かりにくいので)
> update: 画像の仕様変更対応

- app/buttons/recruit/components/create_recruit_buttons.js
- app/buttons/recruit/event/recruit_button_events.js
- app/cmd/other/recruit/other_game_recruit.js
- app/cmd/splat3/recruit/anarchy_recruit.js
- app/cmd/splat3/recruit/fes_recruit.js
- app/cmd/splat3/recruit/regular_recruit.js
- app/cmd/splat3/recruit/salmon_recruit.js
> fix: VC指定時のエラーを修正

- app/cmd/other/friendcode.js
DBからフレンドコードを探して見つからなければフェッチするようにフェッチ位置を変更
> fix: フレンドコードのAPI使用回数軽減

- app/cmd/splat3/show.js
- app/cmd/splat3/stageinfo.js
> Release fix-stage-info-remove-league

- app/common/apis/splatoon3_ink.js
- app/index.js
APIのデータをキャッシュするように変更
ナワバリのスケジュールでフェッチするか決定
グローバル変数で持たせる（メモリ食うようなら変更する予定）
> perf: APIのデータをキャッシュするように変更

- src/app/event/rookie/set_rookie.ts
ブキチが10分後につけるロールが付与じゃなくて置き換えになってたのでロール前とっかえ担ってた問題を修正
> fix: ブキチが通知ロールを外す問題の修正

- src/app/event/rookie/set_rookie.ts
set rookieでロールが更新されるとmembersへの登録するため、ここでは不要になりました。
> 🔧 fix: guidMemberAddからMembersへの登録を削除

- src/app/common/manager/member_manager.ts
- src/app/index.ts
searchDBMemberByIdは画像拾えなければアップデートするように処理修正
> fix: ユーザーアイコンアップデート時にDB更新するように修正

- src/app/index.ts
- src/db/friend_code_service.ts
> fix: guildMemberAddEventでawaitするように変更

- src/app/common/apis/splatoon3_ink.ts
- src/app/feat-recruit/canvases/regenerate_canvas.ts
- src/app/feat-recruit/canvases/salmon_canvas.ts
- src/app/feat-recruit/interactions/commands/salmon_recruit.ts
- src/app/feat-recruit/interactions/modals/salmon_recruit_modal.ts
- src/app/feat-recruit/sticky/recruit_sticky_messages.ts
- src/db/model/recruit.ts
- src/register.ts
- サーモン募集のサブコマ追加
- 合わせるためにビッグランもサブコマ化
> update: バイトチームコンテスト対応

- src/app/index.ts
- 退部時にjoinedAtが読み取れなければDBから探す用に変更
- DBからも読み取れない場合はメッセージに入部日と入部期間を表示しないように変更
> update: 退部メッセージ変更

- src/app/event/rookie/set_rookie.ts
- src/app/feat-recruit/buttons/create_recruit_buttons.ts
- src/app/feat-recruit/interactions/buttons/join_event.ts
- src/app/feat-recruit/interactions/commands/private_recruit.ts
- src/app/feat-utils/other/friendcode.ts
- src/db/friend_code_service.ts
- src/db/model/friend_code.ts
- src/db/recruit_service.ts
- src/register.ts
- プラベ募集のヘヤタテURLを募集時に登録できるように変更
- フレンドコードとフレンドコードURLを分けて登録できるように変更
`ALTER TABLE friend_code ADD COLUMN url TEXT;`
> update: ヘヤタテ機能対応とフレンドコードのURL登録対応

- package.json
- src/app/common/apis/splatoon3_ink.ts
- src/app/common/datetime.ts
- src/app/common/others.ts
- src/app/feat-recruit/buttons/create_recruit_buttons.ts
- src/app/feat-recruit/canvases/anarchy_canvas.ts
- src/app/feat-recruit/canvases/big_run_canvas.ts
- src/app/feat-recruit/canvases/event_canvas.ts
- src/app/feat-recruit/canvases/fes_canvas.ts
- src/app/feat-recruit/canvases/regenerate_canvas.ts
- src/app/feat-recruit/canvases/regular_canvas.ts
- src/app/feat-recruit/canvases/salmon_canvas.ts
- src/app/feat-recruit/interactions/commands/event_recruit.ts
- src/app/feat-recruit/interactions/modals/anarchy_recruit_modal.ts
- src/app/feat-recruit/interactions/modals/event_recruit_modal.ts
- src/app/feat-recruit/interactions/modals/extract_recruit_modal.ts
- src/app/feat-recruit/interactions/modals/recruit_edit.ts
- src/app/feat-recruit/modals/create_event_modal.ts
- src/app/feat-recruit/modals/create_recruit_modals.ts
- src/app/feat-recruit/sticky/recruit_sticky_messages.ts
- src/app/feat-utils/splat3/show.ts
- src/app/handlers/command_handler.ts
- src/app/handlers/modal_handler.ts
- src/constant.ts
- src/db/model/recruit.ts
- src/register.ts
環境変数追加
- `CHANNEL_ID_RECRUIT_EVENT`
- `ROLE_ID_RECRUIT_EVENT`
> feat: イベントマッチ募集機能追加

- src/app/feat-recruit/canvases/big_run_canvas.ts
- src/app/feat-recruit/canvases/regenerate_canvas.ts
canvasの方の差分はtry-catch消しただけです
Close #553
> update: ビッグランの参加状況表示対応

- src/app/common/apis/splatoon3_ink.ts
- src/app/common/others.ts
- src/app/feat-recruit/canvases/anarchy_canvas.ts
- src/app/feat-recruit/canvases/big_run_canvas.ts
- src/app/feat-recruit/canvases/event_canvas.ts
- src/app/feat-recruit/canvases/fes_canvas.ts
- src/app/feat-recruit/canvases/regular_canvas.ts
- src/app/feat-recruit/canvases/salmon_canvas.ts
- src/app/feat-recruit/interactions/commands/anarchy_recruit.ts
- src/app/feat-recruit/interactions/commands/salmon_recruit.ts
- src/app/feat-recruit/interactions/modals/anarchy_recruit_modal.ts
- スケジュールデータが更新されていない時、時間外データを排除
- dispanderでメッセージ本文がないメッセージを取得した時のエラーを修正
> fix: 募集用スケジュールデータの扱い変更, dispanderの処理変更

- src/app/common/apis/splatoon3_ink.ts
Close #603 ←バグの原因が違ったけれど、修正したのでクローズ
> fix: スケジュールがフェッチされない問題を修正

- src/app/common/apis/splatoon3.ink/splatoon3_ink.ts
- src/app/feat-recruit/interactions/commands/anarchy_recruit.ts
- src/app/feat-recruit/interactions/commands/event_recruit.ts
- src/app/feat-recruit/interactions/commands/fes_recruit.ts
- src/app/feat-recruit/interactions/commands/regular_recruit.ts
- src/app/feat-recruit/interactions/commands/salmon_recruit.ts
- src/app/feat-recruit/interactions/modals/extract_recruit_modal.ts
- src/app/feat-recruit/interactions/modals/salmon_recruit_modal.ts
- src/app/feat-utils/splat3/show.ts
- src/app/feat-utils/splat3/stageinfo.ts
- src/app/feat-utils/team_divider/divider.ts
- src/app/handlers/message_handler.ts
- show nawabariのエラー修正
- dividerで観戦者がいないときにエラーが出るのを修正
> fix: 各種バグ修正

- src/app/feat-admin/joined_date_fixer/fix_joined_date.ts
- src/app/handlers/command_handler.ts
- src/constant.ts
- src/db/member_service.ts
- src/register.ts
意外と要請があったので管理用コマンド追加
環境変数にDEVELOPERロールのIDを追加
> feat: 入部日修正コマンドの追加

- src/app/event/rookie/set_rookie.ts
> fix: 新入部員ロールがつかない問題の修正

- package.json
- src/app/common/manager/role_manager.ts
- src/app/feat-admin/ban/ban.ts
- src/app/feat-recruit/interactions/modals/extract_recruit_modal.ts
- src/app/feat-recruit/modals/create_anarchy_modal.ts
- src/app/feat-recruit/modals/create_event_modal.ts
- src/app/feat-recruit/modals/create_fes_modal.ts
- src/app/feat-recruit/modals/create_salmon_modal.ts
- src/app/feat-utils/other/friendcode.ts
- src/app/feat-utils/splat3/buki.ts
- src/app/feat-utils/voice/tts/voice_bot_node.ts
- src/app/index.ts
- src/app/logs/commands/command_log.ts
- TypeScriptのバージョンも上げないと動かなかったので更新
- ユーザープロフィールの名前表示対応
- ユーザータグ使ってたところはusernameに変更
> chore: discord.js v14.12.0 対応

- src/app/feat-recruit/sticky/recruit_sticky_messages.ts
募集〆後にメッセージ打たれるとボタン見えなくなっちゃってたので変更
> update: 簡易募集のボタンを〆時以外のStickyでも表示

- src/app/feat-admin/fest_setting/fest_settings.ts
> fix: コマンドログ二重送信修正

- src/app/feat-utils/voice/vpick.ts
> update: vpickのエラーメッセージ追加

- src/app/constant/button_id.ts
- src/app/constant/constant_common.ts
- src/app/event/rookie/send_questionnaire.ts
- src/app/event/support_auto_tag/send_support_close_button.ts
- src/app/event/vctools_sticky/vc_tools_message.ts
- src/app/event/vctools_sticky/voice_lock.ts
- src/app/feat-recruit/buttons/create_recruit_buttons.ts
- src/app/feat-recruit/interactions/buttons/recruit_button_handler.ts
- src/app/feat-utils/other/friendcode.ts
- src/app/feat-utils/team_divider/divider.ts
- src/app/feat-utils/team_divider/divider_button_handler.ts
- src/app/feat-utils/voice/voice_locker.ts
- src/app/handlers/button_handler.ts
- ID自体を変えているのでできるだけ動きのない時間にマージしたほうが良さげ
> refactor: ボタンのカスタムIDをsnake_camelで統一

- .vscode/settings.json
- .vscode/tasks.json
- package.json
- prisma/migrations/20230827100408_add_key_column_in_sticky_table/migration.sql
- prisma/schema.prisma
- src/app/common/sticky_message.ts
- src/app/constant/sticky_key.ts
- src/app/event/vctools_sticky/vc_tools_message.ts
- src/app/feat-recruit/interactions/buttons/cancel_event.ts
- src/app/feat-recruit/interactions/buttons/cancel_notify_event.ts
- src/app/feat-recruit/interactions/modals/recruit_edit.ts
- src/app/feat-recruit/sticky/recruit_sticky_messages.ts
- src/db/sticky_service.ts
- `Sticky`テーブルに`key`カラム追加
- 既存のテーブルはDROP(別に保持しておく必要はないので)
> update: VCToolsのオンボーディングメッセージをSticky化

- src/app/feat-utils/voice/tts/discordjs_voice.ts
- src/app/feat-utils/voice/tts/voice_bot_node.ts
- 単芝以外を「わらあた」一回に変更
- 省略文字数を150文字までに変更
- 読み上げメッセージをキューで管理するように変更
> update: 読み上げで8切りされないように修正

- prisma/migrations/20230828130236_add_recruit_count_and_voice_count/migration.sql
- prisma/schema.prisma
- src/app/event/voice_count/voice_count.ts
- src/app/feat-recruit/interactions/buttons/close_event.ts
- src/app/feat-recruit/interactions/buttons/close_notify_event.ts
- src/app/feat-recruit/interactions/buttons/recruit_count.ts
- src/app/handlers/vcState_update_handler.ts
- src/app/index.ts
- src/db/recruit_count_service.ts
- src/db/voice_count_service.ts
- `voice_count`と`recruit_count`テーブルを作成
> feat: VC使用時間と募集回数をカウント

- src/app/feat-utils/voice/tts/discordjs_voice.ts
> fix: 読み上げメッセージが空のときキューに入れない

- src/app/index.ts
- [setActivity](https://old.discordjs.dev/#/docs/discord.js/main/class/ClientUser?scrollTo=setActivity) (discord.js Docs)
- [ActivityType](https://discord-api-types.dev/api/discord-api-types-v10/enum/ActivityType) (discord.js Docs)
> update: ステータス表示をプレイ中からカスタムに変更

- src/app/feat-utils/voice/tts/discordjs_voice.ts
- src/app/index.ts
- 読み上げ中に落とすとisPlaying=trueのままになり読み上げなくなっていたので、Join&Kill時にキューリセット&isPlaying=falseに
- でし！がVC参加してなくても8切りするのを修正
- 開発時いちいちブキチを切断しなくてもいいように起動時に自動切断
少なくとも呼び出し時に喋らないことはなくなるはず…。
途中で喋らなくなったらとりあえず8切りすれば喋るようにはなるはず。
> fix: ブキチが読み上げない問題を修正

- src/app/common/apis/splatoon3.ink/splatoon3_ink.ts
`festSetting` -> `festSettings`
> refactor: 変数名修正

- src/app/common/apis/splatoon3.ink/splatoon3_ink.ts
- src/app/common/apis/splatoon3.ink/types/bankara_properties.ts
- src/app/common/apis/splatoon3.ink/types/fest_properties.ts
- src/app/feat-recruit/interactions/commands/fes_recruit.ts
- src/app/feat-recruit/interactions/modals/extract_recruit_modal.ts
- src/app/feat-utils/splat3/show.ts
> Release 2023-09-10 18:43:59 +0900

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/post-create.sh
- .devcontainer/prebuild.sh
- codespacesやローカルの開発環境用にdevcontainer設定を追加
> chore: 開発コンテナ設定の追加

- src/app/feat-utils/voice/tts/discordjs_voice.ts
This reverts commit 9e50c32e9f720650e4a0980c20e60bcec4432dbe.
> Revert "refactor: AbortControllerのnewを1箇所に"

- package.json
- prisma/migrations/20231011100857_add_rookie_flag_in_member_table/migration.sql
- prisma/schema.prisma
- src/app/common/manager/member_manager.ts
- src/app/event/rookie/remove_rookie.ts
- src/app/event/rookie/set_rookie.ts
- src/app/feat-recruit/interactions/modals/extract_recruit_modal.ts
- src/app/handlers/message_handler.ts
- src/app/index.ts
- src/db/member_service.ts
- サーバ参加時にはフラグのみで判定
- ロールを外すときにフラグを一緒に外す
- 保存用にメッセージコマンドを作成 (使い終わったら削除予定)
- Memberテーブルのレコード追加や、アップデートの処理を変更
> update: 新入部員ロールの管理用フラグをMemberテーブルに追加

- src/app/common/manager/member_manager.ts
- isUrlValidで得たフラグが逆で使用されていたのを修正
> fix: アイコンURLの有効性の確認結果を逆に使用していたのを修正

- src/app/feat-recruit/interactions/commands/regular_recruit.ts
- src/app/feat-recruit/interactions/commands/salmon_recruit.ts
- src/app/handlers/command_handler.ts
- サーモン募集とナワバリ募集だけdeferReplyの位置を修正し忘れていたのを修正
- commandHandlerに例外処理追加(Discordへのエラー通知)
> fix: 募集のreplyがタイムアウトする問題の修正

- src/app/feat-recruit/interactions/buttons/confirm_join_request.ts
> fix: キャンセル後に参加拒否ボタンを押したときのエラーを修正

- src/app/event/vctools_sticky/vc_tools_message.ts
- src/app/feat-recruit/interactions/buttons/cancel_event.ts
- src/app/feat-recruit/interactions/buttons/cancel_notify_event.ts
- src/app/feat-recruit/interactions/buttons/confirm_join_request.ts
- src/app/feat-recruit/interactions/modals/recruit_edit.ts
- src/app/feat-recruit/sticky/recruit_sticky_messages.ts
> feat: stickyメッセージを@silentに設定
